class PositionState:
    UNDEFINED_POSITION = 0
    NOT_TEACHED = 1
    UNREFERENCED = 2
    OPEN = 3
    CLOSED = 4
    PARTIALLY_OPEN = 5
    VENTILATION_POSITION = 6
    INTERMEDIATE_POSITION = 7
    RWA_POSITION = 8
